defaults: &defaults
  TIMEZONE: 'Paris'

  REDIS_URL:      redis://localhost:6379
  REDIS_PASSWORD: ~
  REDIS_CLUSTER:  false

  URL_HOST:                peatio.tech
  URL_ROOT_PATH:           '/'
  URL_SCHEME:              http
  FORCE_SECURE_CONNECTION: 'false'

  LOG_LEVEL: ~

  API_CORS_ORIGINS:           '*'
  API_CORS_ALLOW_CREDENTIALS: 'false'
  API_CORS_MAX_AGE:           ~

  SENTRY_DSN_BACKEND:  ~

  METADATA_TITLE:       Peatio Exchange
  METADATA_DESCRIPTION: The Opensource Cryptocurrency Exchange
  METADATA_KEYWORDS:    Peatio,Opensource,Exchange,Cryptocurrency

  JWT_PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF1ZlVoK3BES3lqR005MFRFckNDagoreE5jb2w0Q2FTdnlaaVJtMGtjTFZBK0lGcnFRdUJzTUIwYVRQUlJwL2lHRnIvRUFtSC9uVXdmd2N2aHRMeUZsCi9LanpDSGUrdFBrYVlZUzgvVGc1YXh6bENHd1l0QkJMUDUwV0NmclNWZnlTWEFOSWdvdXZsSmU1OXJDcGw2UmUKeU5XVlpYUnFLcXc3d0JoRFJndnRsSXF5SWpjS0JLcGQyZUJ4YjBBb2dpTzdVbFdSRDU0SjN1QVhpSzllUllCTwpEYjYvN1Btand6THI5b2VYa2JkZ1ZPb3NRczdpVDZDcnhaaXkwQStjeldXaHZheEdXTmNmMjJRSWtGS20wcENKCjAxZkR5OEtiL3B0cXFMWDNkNUxaeUU5ajFJaXFzRE4ya3BjREJNN0NXVDQvQnJNMHo3dU5JQWxPMUVjRE5xT0wKcFFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
  JWT_ALGORITHM: RS256
  JWT_ISSUER: ~
  JWT_AUDIENCE: peatio
  JWT_DEFAULT_LEEWAY: ~
  JWT_ISSUED_AT_LEEWAY: '180'
  JWT_EXPIRATION_LEEWAY: ~
  JWT_NOT_BEFORE_LEEWAY: ~
  PEATIO_JWT_PRIVATE_KEY: ~

  SCOUT_KEY:       ~
  SCOUT_APP_NAME:  ~
  SCOUT_LOG_LEVEL: warn
  SCOUT_ENV:       production

  MINIMUM_MEMBER_LEVEL_FOR_DEPOSIT:  '3'
  MINIMUM_MEMBER_LEVEL_FOR_WITHDRAW: '3'
  MINIMUM_MEMBER_LEVEL_FOR_TRADING:  '3'

  EVENT_API_JWT_PRIVATE_KEY: ~
  EVENT_API_JWT_ALGORITHM:   RS256

  EVENT_API_RABBITMQ_URL:      ~
  EVENT_API_RABBITMQ_HOST:     localhost
  EVENT_API_RABBITMQ_PORT:     "5672"
  EVENT_API_RABBITMQ_USERNAME: guest
  EVENT_API_RABBITMQ_PASSWORD: guest

  RANGER_HOST: '0.0.0.0'
  RANGER_PORT: '8081'
  RANGER_CONNECT_SECURE: 'false'

  BULLET: 'false'

  ENABLE_ACCOUNT_WITHDRAWAL_API: 'true'

  VAULT_ADDR:   http://127.0.0.1:8200
  VAULT_TOKEN:  ""

  MAX_CURRENCIES: ~
  MAX_MARKETS:    ~

development:
  <<: *defaults
  EVENT_API_JWT_PRIVATE_KEY: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBb3VLVHh2SFVJVDJENmdXaWJRcS9kbW9BUUwyeWJ6SGFiUXRlc1AyL2o1VjkvUExaCmhHNWtLVkpPWjcxVVdMQ3BjZTQxeHZzQ0lKd0Q5MnVDNW5Lak5wblRDTWpwTUJNMGg0aFF4a2VOeHdNeU41N1gKM1QzbWFCVmZzUTNCblErSm84L0tzdUxhODlvY0dDeDgvYlUyOGNld2FxRk8ydUVMWWJiaUZadGFCenFJd0ZCdQpTM3hGQmt6NE16MGgvWEIxTjl5ZDg5d25OMm1oWVBsU0xrTGVUdFoyeWswK2krZHhZd2V4MEozOXJDS0hnRWRKCko1NTZHNmdtZWpJZ3dtcHNVeHJpdkVJRU5jR09POHdmQVBUVy92SFZmc2ROTExHejRtZE9CWmxsa2orcFFQODYKTnFSUjRKSnFDdEg3dHYyaXVBSGI4NnB5anVlZkVGU3ljMmxZRXdJREFRQUJBb0lCQUJrUlViamVZczB5MEdobApzWmVpZmREVmczQnpRVkRIbFZ3TzBlWGZSMm5ya2RZcDhidmwyVmhhcUdKaXl1WlRXZUNFenBYdTcyYmhXK0xxCkV0MHdhMW50MW9LVm1QMmpGd1I4d0NHanhYZ0pUK01yZVFFOWs0WVZOQUxsb1JSdzNiZnVOTDNQRis5TGMrTnMKaFZmdVdhUmdIUkJyL3R6RW9hSEtLWVUxd1djM0poSitNRklNVkZBT0RvaGp6bXNlV2lzTDNnbzVrUC9KYUpVZwprNm13Wnd0QzRvQ3pPQ3FoRGF0WVI3cktJbXMyS1lCNVBwaTRDTThkRzJGTzBwWGxXUU9XT0t2N01TUjlVeEtzCmd4YWFRRlhjajBQM2lSRFVQMDRkSWtqblNtemZmR0F2L3lBTHovZjk0V1lIK3gvd01DWms4ejJ4bnRJclllM3UKN0NOd045RUNnWUVBMEplcThCaXlKczF6YlBpcTlWWnR5L3R0M1dhaXJDbUl4cXRwU2syVU9UNmh2TldiMTUxVwpBMGRWYWEvSVBhdDV4ZkNWdGhkNlB3UGpJbWVPVXQ4Mlhib2JYeE8zREJUcmVzTlRNWUhiMGVUK09sSG04SU5uCnVwOGFxZWpWejc1ME5VYUxGWWpxWk1wVVR1Z2FVREIzNWZ1bXg0SXliNm5LRGMvSStrN25qUlVDZ1lFQXgrZVAKcE4vR1dqYjJUOU1CUm1xdkVtSGxKOXBZSEZpWGZlWnJHdzg3Q2E5WjVDYVp1VzBrSVAwSlhWSDZOOThqL2RvbApDTHZPdE5oZVFoaGUrTU91VXJMT0ttaytpckM5SEk2cW9aT3Nkc0lCc0pXSHdPanB1UW00OWNvdXc0K2ZKOWRxCjN2cTE2bG5EQlNoRU5HTEFhdVBzWDhLRUlYVzhRRnBDM3ppbXFvY0NnWUI2bTh2VVdRL09reEQzeXFyaWpxejMKSzVFR2hKKzF4cXdvNnZSMndtY1B4dXJXemxCT1NxTVdSa1hFVzVpOTl4OGE
