secret_key: changemeplease # You can remove this line if unused

locked:
  - suspicious
  - lock

document_types:
  - Passport
  - Identity card
  - Driver license
  - Utility Bill
  - Residental
  - Institutional
  - Address

user_storage_titles:
# - personal
# - company

—Åaptcha_protected_endpoints: []
# - user_create
# - session_create
# - password_reset
# - email_confirmation

jwt:
  enabled: true
  expiration_time: 3600
  algorithm: RS256
  secret_key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBdWZVaCtwREt5akdNOTBURXJDQ2oreE5jb2w0Q2FTdnlaaVJtMGtjTFZBK0lGcnFRCnVCc01CMGFUUFJScC9pR0ZyL0VBbUgvblV3Zndjdmh0THlGbC9LanpDSGUrdFBrYVlZUzgvVGc1YXh6bENHd1kKdEJCTFA1MFdDZnJTVmZ5U1hBTklnb3V2bEplNTlyQ3BsNlJleU5XVlpYUnFLcXc3d0JoRFJndnRsSXF5SWpjSwpCS3BkMmVCeGIwQW9naU83VWxXUkQ1NEozdUFYaUs5ZVJZQk9EYjYvN1Btand6THI5b2VYa2JkZ1ZPb3NRczdpClQ2Q3J4Wml5MEErY3pXV2h2YXhHV05jZjIyUUlrRkttMHBDSjAxZkR5OEtiL3B0cXFMWDNkNUxaeUU5ajFJaXEKc0ROMmtwY0RCTTdDV1Q0L0JyTTB6N3VOSUFsTzFFY0ROcU9McFFJREFRQUJBb0lCQVFDdGMvT1B6c0w1T3FMcwplaDZoRjRrZFJ3QWZDMlZnU0hlL3dyQ043MnFuckIwYVprZGJFdzl6TWVkaEQ4dVdHaHFpOUQvRC8zbjhQdW1QCnRCM1QybWxROVI1TWhiVkRCU0FRV2tvV1AvMSs1ZUxVcWsrWWxhSTY0Z0dPcVlETVo5ejFLckxWNGdtU3BydjEKV08rMzNMLzB3UlNySDUxdjFGdWZZSUpQc2d5WGdmaHBHQVdKOFh2RXA5U1V4bit1TWkvemZQMnVzcjRHY3p0SwpuTXgyaUdjNGdKZGdFTVdublUweklISXFoN1VtbGdnUmNaZG94Nk8weGN2WUFBdkhSLzFFNXhjT2FCRmRJbzRKCnJ0eTJqK3BqcTJmbndIN05pN09kR2o1ek5Rb2RrVms3aWdrZ2paeG5FVEtWZ01vTS9ReG5EQjA1Sk5rNGN3blEKb3dGQ2NmYkJBb0dCQU43MmprUzRVUWJXdjNCYXdEMERvVDZtWWZENlpYUHZhRDhrY29JckZ5MFg1ZmdWR1ZVQgpGZUs3VHAzODZ0RFdKaUVESE1ZVkt4T3llWU5kakpKQThSb2V1cGNvS0NZM0dxWnVRbW1oUFFJaDQyWkFBZEUrClkwOUJiVmFEdlRKM0ZsUnQvMXBoS1RjWWswODQzZ1hjNFFmc1hmbC9kaWVDdGd4b2d4NUMyQTg5QW9HQkFOV0MKNFlFYXM5c3JqUngzT2dZUEE2NE9OL0xSZkYvc3N1MkQ5S3FCZGRnTUNOY2VHdHpTelU0dGE4cm9pZXozTDJRawpKRGM4ODIxS1drRjlPNngzNjFHSk14VEZmdzh5Q3oxcDJNeWdpd3hCWTlWeU1HbEVaRzBEQ1cycG95anp3T2FLCmFZQWJGVWh4ckk1Rlk1d0JsT3BkZ3V0Zkl6Q0NBdWNsSmF2a1J6U0pBb0dBRVJzUlp5eE02eDFtcXBRTDA2S0gKcUdyVGNNMkZJeFBuQjVFZ1IrUk9idU02ZllJQTQ0aWx5VE5kb0xsYXVwTHpjZXp2TkRORGpzdE9qMG1LRTE1dwpJUFRpazk0ODFsRzc5YkRYMzRyRFIzcWFHNm9sZVl3enlreld1cUI0ejNwYmVEYklOSUxueXBaVUZ1dmgvTWtwCmFwWXp6NFI3NkNRYkczQ1pQcVVhTm5FQ2dZRUF0cy96cVlsbGlqbUYvMk9PaVBWK0h5QUpnNTBlc3p1R0VKdzEKZDNDVnFFRFZxT3NiOFF1RnduUmRvVVR1STdtYUdGSmh0L0kyTTlPLzUrY0VteTJxalF1K2N3Q1BSRUdESWpobwo2dnhqVWtFQzdCVnpvZzV2Tm0rdE9QcFF1NVhLQ3h0a0xjNENzUjZ6c3JWekRuYkVQTStJYzJQb1MzWm1hZWVDCmsrVkhtcEVDZ1lFQWtac1hlS3cycGVOUWtaNytlOGhUWmZiYlBpWnpZejFKVDFZaWlDQ0dXTklWMWNOczF4c2IKV0M2d0M0dHBUQ0NHb25zbk1YWFp2VlJWM2w4emwvaGJPQWJzNzVXdDJjWXkxdjFDbzlxZzJiN1NadEwrdzM0WQo3aHhuRVpxeWhsZFZnZDcvZE4zUUZtNmR1YXBoRXZETHJ0eWRCM3YzR3ErYm5ZK3Q0MU9JdnJ3PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

sms:
  enabled: true
  provider: kavenegar
  kavenegar:
    api_key: "52626E6634336D72514F562F51503349526D677775673D3D"
    sender: "10000300004004"
